name: Deploy to Cloud Run

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    name: Setup, Build, Publish, and Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Setup gcloud CLI
      - uses: google-github-actions/setup-gcloud@v0
        with:
          service_account_email: ${{ secrets.GCP_SA_USERNAME }}.iam.gserviceaccount.com
          service_account_key: ${{ secrets.GOOGLE_CREDENTIALS }}
          export_default_credentials: true

      # Configure Docker with Credentials
      - name: Configure Docker
        run: |
          gcloud auth configure-docker

      # Build the Docker image
      - name: Build & Publish
        run: |
          gcloud config set project ${{ secrets.GCP_PROJECT_ID }}
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/bigquery-cloudbuild
          gcloud config set run/region europe-west3

      # Deploy the Docker image to the GKE cluster
      - name: Deploy
        run: |
          gcloud run deploy bigquery-cloudbuild --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/bigquery-cloudbuild \
          --platform managed 
